### ISSUE TITLE
Formulaire statique, édition d'un projet

### ISSUE THREAD

**Issue by NoeBerdoz** [antistatique/citadel#124]
### 💬Ajout d'un formulaire édition d'un projet

Édition du formulaire avec les champs statique éditables suivants :
  - [x] Status de maintenance (on/off)
  - [x] Status du projet `select` (ENUM `en cours de dev`, `publié`, `archivé`) 
  - [x] Nom
  - [x] Numéro
  - [x] Liens des outils connexes (multiple links -> entities with relations)
  - [x] Liens des environnements (multiple envs -> entities with relations)
  - [x] Date de mise en prod

**Comment by WengerK** [comment]
We have to create it's own issue for "Date de dernière release" explaining it must be linked with a Github Repository + Config (branch to fetch last tag)
