### ISSUE TITLE
Détails statique d'un projet

### ISSUE THREAD

**Issue by NoeBerdoz** [antistatique/citadel#125]
### 💬 Création d'une view de détails statique d'un projet

Require #120

- [x] Lien du projet depuis la liste #120 

Affichage des éléments suivants :
  - [x] Status de maintenance (on/off)
  - [x] Status du projet `select` (ENUM `en cours de dev`, `publié`, `archivé`) 
  - [x] Nom
  - [x] Numéro
  - [x] Liens des outils connexes
  - [x] Liens des environnements
  - [x] Date de mise en prod

**Comment by WengerK** [comment]
We have to create it's own issue for "Date de dernière release" explaining it must be linked with a Github Repository + Config (branch to fetch last tag)
