### ISSUE TITLE
Attribution de rôle aux membres

### ISSUE THREAD

**Issue by NoeBerdoz** [antistatique/citadel#131]
### 💬 Attribution de rôle décisionnel aux membres

Altération de l'attribution de membre à un projet avec un système de "sous-forme"

Is contained by #129 Attribution d'un projet à des membres

- [x] Update Entity Member avec rôle (ENUM)
- [x] Altération de l'attribution de membre à un projet avec un sous-forme permettant
	- Choix d'un membre dans un `select`
	- Champ `select` du rôle

**Comment by WengerK** [comment]
C'est fait non ? @NoeBerdoz
